server:
  port: 7001
eureka:
  instance:
    hostname: jichi-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
